package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, QUIT,

	PING,PONG,CLONE_GITFILE,

	ADD_GITFILE, ASK_PULL, TELL_PULL, COMMIT, CONFLICT, DELETE,


	TEAM_UPDATE, TELL_PULL_TEAM, TEAM_INFO
}
